version: "3.7"

services:

  framework:
    image: "billing:latest"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "./:/home/node/workspace"
    networks:
      - automation
    stdin_open: true
    tty: true
    environment:
      - ENV=${ENV}
      - SERVER_IP=${SERVER_IP}
      - SUIT=${SUIT}
      - LOG_LEVEL=${LOG_LEVEL}
      - TEST_REPORTER=${TEST_REPORTER}
    depends_on:
      - selenoid

  selenoid:
    image: "aerokube/selenoid:1.10.5"
    ports:
      - "4444:4444"
    volumes:
      - "./config/selenoid:/etc/selenoid"
      - "/home/workspace/node/selenoid/video:/opt/selenoid/video"
      - "./selenoid/logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/selenoid/video
    command:
      [
        "-conf", "/etc/selenoid/browsers.json",
        "-video-output-dir", "/opt/selenoid/video",
        "-log-output-dir", "/opt/selenoid/logs",
        "-timeout", "30m",
        "-max-timeout", "30m",
        "-container-network", "billing-ui_automation",
        "-video-recorder-image", "selenoid/video-recorder:7.1"
      ]
    networks: 
      - automation

  selenoid-ui:
    image: "aerokube/selenoid-ui:1.10.4"
    networks:
      - automation
    depends_on:
      - selenoid
    restart: always
    ports:
      - "8811:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]


networks:
  automation:
    driver: bridge