import {
  AbonentsPage,
  AcceptanceAccountsPage,
  AdditionalEquipmentPage,
  AddMoney145888Page,
  AddNewSubscriberPage,
  AddNewsWindowPage,
  AdminPage,
  AdminServiceSectionsAddApplicationPage,
  AdminServiceSectionsAddEventPage,
  AdminServiceSectionsPage,
  ApplicantionSearchPage,
  ApplicantPage,
  AvailabilityEquipmentPage,
  BackConnectionB2ServiceSectionsPage,
  BackConnectionLegalEntitiesServiceSectionsPage,
  BackConnectionServiceSectionsPage,
  Billing,
  BillingPage,
  BonusReportPage,
  CableModelsPage,
  CardInformationPage,
  CentrEngineersServiceSectionsPage,
  ConnectionsAndRepairsPage,
  CtvApplicantAddConnectionsPage,
  CtvApplicantAddEventPage,
  CtvApplicantAddRepairsPage,
  CtvApplicantPage,
  CtvServicesPage,
  D135EngineersServiceSectionsPage,
  EngineersNorthAddAbpPage,
  EngineersNorthAddAdminDoingPage,
  EngineersNorthAddCallsPage,
  EngineersNorthAddConnectionPage,
  EngineersNorthAddDevelopmentPage,
  EngineersNorthAddInspectionPage,
  EngineersNorthAddModernizationPage,
  EngineersNorthAddRepairPage,
  EngineersNorthServiceSectionsPage,
  EngineersTransportNetworksAddEventPage,
  EquipmentPage,
  HashtagsPage,
  HomePage,
  IncomingPaymentsPage,
  InternetApplicantAddCallsPage,
  InternetApplicantAddConnectionsPage,
  InternetApplicantAddConnectionsPeriodPage,
  InternetApplicantAddEventPage,
  InternetApplicantAddExtendedServicesPage,
  InternetApplicantAddMovingPage,
  InternetApplicantAddRepairsPage,
  InternetApplicantPage,
  InternetApplicantTimePlusPage,
  InternetServicesPage,
  IptvOttProductsPage,
  ListConnectionPendingPage,
  LocalizationSectionsPage,
  LogApplicantPage,
  LoginPage,
  LogisticsPage,
  MenuPage,
  NordEngineersServiceSectionsPage,
  OfficeNetworkServiceSectionsPage,
  OperationsPrivatbankPage,
  OptionalEquipmentPage,
  OrdersForPayment,
  OrderTypesPage,
  PreconditionsPage,
  PrivatbankStatisticPaymentsPage,
  ProgrammersServiceSectionsAddBugPage,
  ProgrammersServiceSectionsAddEventPage,
  ProgrammersServiceSectionsAddRequirementPage,
  ProgrammersServiceSectionsPage,
  ScratchCardInfoPage,
  ScratchCards,
  ScratchCardsListAdd,
  SearchInternetRequestPage,
  SoftwareEngineersServiceSectionsPage,
  StaffServiceSectionsPage,
  SubscriberPage,
  SuppliersPage,
  SystemMagazinePage,
  TechnicalSupportAddCallPage,
  TechnicalSupportAddEventPage,
  TechnicalSupportAddRepairPage,
  TechnicalSupportServiceSectionsPage,
  TransportEngineersServiceSectionsPage,
  UnionServicesPage,
  UserAddMoneyPage,
  UserEmailPage,
  UserFinderPage,
  VideoServersPage,
  ViewUserInfoPage,
  ViewUserInfoPopUpPage,
  OfficeNetAddEventPage,
  OfficeNetAddRepairPage,
  StaffAddEventPage,
  StaffAddHrApplicantPage,
  AdditionNotePage,
  DonePage,
  ClosePage,
  TurnPage,
  MarkTransferredPage,
  AppointPerformerPage,
  GiveAppointPage,
} from "./pages";


export const webPages = () => ({
  billing: new Billing(),
  menu: new MenuPage(),
  loginPage: new LoginPage(),
  userEmail: new UserEmailPage(),
  userAddMoney: new UserAddMoneyPage(),
  homePage: new HomePage(),
  addNewSubscriber: new AddNewSubscriberPage(),
  subscriber: new SubscriberPage(),
  billingPage: new BillingPage(),
  systemMagazine: new SystemMagazinePage(),
  adminPage: new AdminPage(),
  cableModels: new CableModelsPage(),
  addEquipment: new AdditionalEquipmentPage(),
  suppliers: new SuppliersPage(),
  ordersForPayment: new OrdersForPayment(),
  bonusReportPage: new BonusReportPage(),
  viewUserInfoPage: new ViewUserInfoPage(),
  viewUserInfoPopUpPage: new ViewUserInfoPopUpPage(),
  orderTypes: new OrderTypesPage(),
  hashtagsPage: new HashtagsPage(),
  operationsPrivatbankPage: new OperationsPrivatbankPage(),
  cardInformationPage: new CardInformationPage(),
  addMoney145888Page: new AddMoney145888Page(),
  scratchCardInfoPage: new ScratchCardInfoPage(),
  scratchCards: new ScratchCards(),
  scratchCardsListAdd: new ScratchCardsListAdd(),
  acceptanceAccountsPage: new AcceptanceAccountsPage(),
  connectionsAndRepairsPage: new ConnectionsAndRepairsPage(),
  internetApplicantPage: new InternetApplicantPage(),
  internetApplicantTimePlusPage: new InternetApplicantTimePlusPage(),
  internetApplicantAddEventPage: new InternetApplicantAddEventPage(),
  internetApplicantAddConnectionsPage: new InternetApplicantAddConnectionsPage(),
  internetApplicantAddConnectionsPeriodPage: new InternetApplicantAddConnectionsPeriodPage(),
  internetApplicantAddMovingPage: new InternetApplicantAddMovingPage(),
  internetApplicantAddRepairsPage: new InternetApplicantAddRepairsPage(),
  internetApplicantAddExtendedServicesPage: new InternetApplicantAddExtendedServicesPage(),
  internetApplicantAddCallsPage: new InternetApplicantAddCallsPage(),
  ctvApplicantPage: new CtvApplicantPage(),
  adminServiceSectionsPage: new AdminServiceSectionsPage(),
  softwareEngineersServiceSectionsPage: new SoftwareEngineersServiceSectionsPage(),
  centrEngineersServiceSectionsPage: new CentrEngineersServiceSectionsPage(),
  nordEngineersServiceSectionsPage: new NordEngineersServiceSectionsPage(),
  d135EngineersServiceSectionsPage: new D135EngineersServiceSectionsPage(),
  backConnectionServiceSectionsPage: new BackConnectionServiceSectionsPage(),
  backConnectionB2ServiceSectionsPage: new BackConnectionB2ServiceSectionsPage(),
  backConnectionLegalEntitiesServiceSectionsPage: new BackConnectionLegalEntitiesServiceSectionsPage(),
  officeNetworkServiceSectionsPage: new OfficeNetworkServiceSectionsPage(),
  technicalSupportServiceSectionsPage: new TechnicalSupportServiceSectionsPage(),
  transportEngineersServiceSectionsPage: new TransportEngineersServiceSectionsPage(),
  staffServiceSectionsPage: new StaffServiceSectionsPage(),
  searchInternetRequestPage: new SearchInternetRequestPage(),
  equipmentPage: new EquipmentPage(),
  availabilityEquipmentPage: new AvailabilityEquipmentPage(),
  userFinderPage: new UserFinderPage(),
  privatbankStatisticPaymentsPage: new PrivatbankStatisticPaymentsPage(),
  addNewsWindowPage: new AddNewsWindowPage(),
  listConnectionPendingPage: new ListConnectionPendingPage(),
  incomingPaymentsPage: new IncomingPaymentsPage(),
  videoServersPage: new VideoServersPage(),
  preconditionsPage: new PreconditionsPage(),
  logisticsPage: new LogisticsPage(),
  applicantPage: new ApplicantPage(),
  ctvApplicantAddEventPage: new CtvApplicantAddEventPage(),
  ctvApplicantAddConnectionsPage: new CtvApplicantAddConnectionsPage(),
  ctvApplicantAddRepairsPage: new CtvApplicantAddRepairsPage(),
  localizationSectionsPage: new LocalizationSectionsPage(),
  optionalEquipmentPage: new OptionalEquipmentPage(),
  abonentsPage: new AbonentsPage(),
  internetServices: new InternetServicesPage(),
  ctvServicesPage: new CtvServicesPage(),
  iptvOttProductsPage: new  IptvOttProductsPage(),
  unionServicesPage: new UnionServicesPage(),
  applicantLogPage: new LogApplicantPage(),
  applicationSearchPage: new ApplicantionSearchPage(),
  adminServiceSectionsAddEventPage: new AdminServiceSectionsAddEventPage(),
  adminServiceSectionsAddApplicationPage: new AdminServiceSectionsAddApplicationPage(),
  programmersServiceSectionsPage: new ProgrammersServiceSectionsPage(),
  programmersServiceSectionsAddEventPage: new ProgrammersServiceSectionsAddEventPage(),
  programmersServiceSectionsAddRequirementPage: new ProgrammersServiceSectionsAddRequirementPage(),
  programmersServiceSectionsAddBugPage : new ProgrammersServiceSectionsAddBugPage(),
  engineersNorthServiceSectionsPage : new EngineersNorthServiceSectionsPage(),
  engineersNorthAddAdminDoingPage: new EngineersNorthAddAdminDoingPage(),
  engineersNorthAddConnectionPage: new EngineersNorthAddConnectionPage(),
  engineersNorthAddRepairPage: new EngineersNorthAddRepairPage(),
  engineersNorthAddDevelopmentPage: new EngineersNorthAddDevelopmentPage(),
  engineersNorthAddModernizationPage: new EngineersNorthAddModernizationPage(),
  engineersNorthAddAbpPage: new EngineersNorthAddAbpPage(),
  engineersNorthAddInspectionPage: new EngineersNorthAddInspectionPage(),
  engineersNorthAddCallsPage: new EngineersNorthAddCallsPage(),
  engineersTransportNetworksAddEventPage: new EngineersTransportNetworksAddEventPage(),
  technicalSupportAddRepairPage: new TechnicalSupportAddRepairPage(),
  technicalSupportAddCallPage: new TechnicalSupportAddCallPage(),
  technicalSupportAddEventPage: new TechnicalSupportAddEventPage(),
  officeNetAddEventPage: new OfficeNetAddEventPage(),
  officeNetAddRepairPage: new OfficeNetAddRepairPage(),
  staffAddEventPage: new StaffAddEventPage(),
  staffAddHrApplicantPage: new StaffAddHrApplicantPage(),
  additionNotePage: new AdditionNotePage(),
  donePage: new DonePage(),
  closePage: new ClosePage(),
  turnPage: new TurnPage(),
  markTransferredPage: new MarkTransferredPage(),
  appointPerformerPage: new AppointPerformerPage(),
  giveAppointPage: new GiveAppointPage(),
})
